[package]
name = "black-hole"
version = "0.53.0-rc.1"
edition = "2024"

[dependencies]
glam = { version = "0.33", features = ["mint"] }
tokio = { version = "1.38.0", default-features = false, features = ["rt"] }
tokio-stream = { version = "0.1.17", features = ["signal"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["tracing"] }
tween = { version = "2.2", features = ["glam"] }

[dependencies.gluon-ipc]
version="0.1.1"
# git = "https://github.com/technobaboo/gluon"

[dependencies.stardust-xr-fusion]
version="0.53.0-rc.1"
# git = "https://github.com/StardustXR/core"

[dependencies.stardust-xr-molecules]
version="0.53.0-rc.1"
# git = "https://github.com/StardustXR/molecules"

# [patch.crates-io.stardust-xr-protocol]
# path = "../../core/protocol"
# [patch.crates-io.stardust-xr-fusion]
# path = "../../core/fusion"

# [patch.crates-io.stardust-xr-molecules]
# path = "../../molecules"
